owner: upptime
repo: upptime
sites:
- name: web-kodexpay
  url: app.kodexpay.com
- name: eos-spaxe-front
  url: spaxe.app
- name: eos-space-front
  url: myofficespace.pro
- name: eos-qtwswap-front
  url: qtwswap.com
- name: eos-kodextoken-front
  url: token.kodexpay.com
- name: eos-golden-token-front
  url: token.mygoldenx.pro
- name: eos-golden-landing
  url: mygoldenx.pro
- name: eos-golden-front
  url: office.mygoldenx.pro
- name: eos-genesys-front
  url: genesysgroup.io
- name: eos-elv-front
  url: myelv.io
- name: mfxbroker-api
  url: mfxbroker-api.kodexpay.com
- name: space-api
  url: space-api.kodexpay.com
- name: kodexpay-api
  url: api.kodexpay.com
- name: golden-token-api
  url: golden-token-api.kodexpay.com
- name: mfxprime-api
  url: mfxprime-api.kodexpay.com
- name: golden-api
  url: golden-api.kodexpay.com

status-website:
  cname: eos-services.kodexpay.com
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Eos Services
  introMessage: Estado de los servicios de Kodexpay

