owner: upptime
repo: upptime
sites:
- name: kodexpay_api
  url: $KODEXPAY_API_URL
- name: web_kodexpay
  url: $WEB_KODEXPAY_URL
- name: treecoin_api
  url: $TREECOIN_API_URL


status_website:
  cname: eos_services.kodexpay.com
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  method: GET
  name: Upptime Eos Services
  introMessage: Estado de los servicios de Kodexpay
